### ISSUE TITLE
Show percentage only?

### ISSUE THREAD

**Issue by aaronrudkin** [kuglee/BatteryExtra#1]
Hi.

My ideal UI for a battery indicator is that the default icon will be percentage only (no battery icon), and when I click on it I see time remaining. Would it be possible to implement this? It would just require making "Icon" a toggle.

**Comment by kuglee** [comment]
I've added this feature In version 1.1. Please test it.

**Comment by kuglee** [comment]
I've added the ability to set this from the "Show" menu in version 1.1.1.
